### ISSUE TITLE
Is there the ability to add an image or sprite for the bar?

### ISSUE THREAD

**Issue by netgfx** [SaFrMo/phaser-percent-bar#3]
The functionality to use graphics, sprite, an image for the bar background and foreground?

**Comment by SaFrMo** [comment]
Not yet, but I'll add that to the todo list!

**Comment by SaFrMo** [comment]
Fixed in v1.1.0. Good note, thanks!

**Comment by netgfx** [comment]
That's great! 
Now let's take this one step forward
- Add the ability to add sprite via JSONAtlas or JSONArray by declaring `key` and `frame` for the fill or background
- Add example and .gif of this functionality
- Add the ability to display the remaining amount of the bar with the following styles ( 10/100, 10%, 100), via `Phaser.Text` or `Phaser.BitmapText`
- Add ability to offset position of the bar
- Add functionality for `horizontal` and `vertical` bars
- Add functionality to stack bars like adding `x` amount of bars on next / on top of the others

Super charge this plugin! :)

If I have time I will try to contribute on adding any of those and PR you

**Comment by SaFrMo** [comment]
@netgfx Excellent ideas - and definitely PR if you can, that'd be great! Creating a new issue with these suggestions.
